# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "pE1HtGVJ7TW7Z5OGGx4T8NjbExDXVBsV9R+mnS9BNbj48tG7WDhifSNP9jpboZbW4nhtpjkYJ049tIJnBbPErvXddkwZrR+SdeH6O8tHsdli65zZgq4R/39q7W17oRxi+alcmUK9D66GvO+OgO8sZlDgxsWUyPnff+z06netOxE2cVggaJeaCrSfF5DX3dUalkd3Z/jVpaZKja3gJHim5S4iR5ddwF3deM3MlF4YFRIDwE8OKeWh04WZOY3QV3txW2rK5dyk+tpNfA7LBk2vUbGkJg/fkPbd0K7WPysRMAlDM1i/8Md0U0c/WHRFTiPgxOscd7QNEdGhE6JerSWrJAJOr2Ry33JnHPkyChcDMuVkFTxJQUBRDPKKExZDZLpIUe5KpCfCOIe6oj9oFYIW/ElDZEft4U3no6ycPLl/v1R3y91w5WcbaB05o8yQ0CG96ih1dZ6qX1tSAn/AUKQe4l/lXenO+5yarIWKpoPTm2Ch9Pv8jtqJRZcZw2x37k3K5c5ZRU0ZmQuVM5aGb4BGb0Km2cWAkuFM/rSzroPLOc39Blxm0pY/kpMqCxcpxeWBUzDX1mT2mRGPlQq+TvEgDyMM55ty8A55ew9xcN2CiNSGLxKcv3ZDutnYfBRc+ItDS/oiRtCxgw5xS9j8sAGAPkuJYWuIvHO7BDD+aTLg9I4="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
