travis:
  secure:
    BINSTAR_TOKEN: pE1HtGVJ7TW7Z5OGGx4T8NjbExDXVBsV9R+mnS9BNbj48tG7WDhifSNP9jpboZbW4nhtpjkYJ049tIJnBbPErvXddkwZrR+SdeH6O8tHsdli65zZgq4R/39q7W17oRxi+alcmUK9D66GvO+OgO8sZlDgxsWUyPnff+z06netOxE2cVggaJeaCrSfF5DX3dUalkd3Z/jVpaZKja3gJHim5S4iR5ddwF3deM3MlF4YFRIDwE8OKeWh04WZOY3QV3txW2rK5dyk+tpNfA7LBk2vUbGkJg/fkPbd0K7WPysRMAlDM1i/8Md0U0c/WHRFTiPgxOscd7QNEdGhE6JerSWrJAJOr2Ry33JnHPkyChcDMuVkFTxJQUBRDPKKExZDZLpIUe5KpCfCOIe6oj9oFYIW/ElDZEft4U3no6ycPLl/v1R3y91w5WcbaB05o8yQ0CG96ih1dZ6qX1tSAn/AUKQe4l/lXenO+5yarIWKpoPTm2Ch9Pv8jtqJRZcZw2x37k3K5c5ZRU0ZmQuVM5aGb4BGb0Km2cWAkuFM/rSzroPLOc39Blxm0pY/kpMqCxcpxeWBUzDX1mT2mRGPlQq+TvEgDyMM55ty8A55ew9xcN2CiNSGLxKcv3ZDutnYfBRc+ItDS/oiRtCxgw5xS9j8sAGAPkuJYWuIvHO7BDD+aTLg9I4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
